firstmvc/passwordvalidation/Models/Employee.cs
namespace passwordvalidation.Models;
public class Employee{

    public string FirstName{get;set;}
    public string LastName{get;set;}
    public string Email{get;set;}
    public string ContactNumber{get;set;}
    public string Password{get;set;}

}

firstmvc/passwordvalidation/Models/EmployeeManager.cs
namespace passwordvalidation.Models;
using System.Collections.Generic;
using System.IO;
using System.Text.Json;
using System.Text.Json.Serialization;

public class EmployeeManager{


    public static List<Employee> GetAllEmployees(){
        // List<Employee> emp = new List<Employee>();
        // emp.Add( new Employee(){ FirstName="Ravi", LastName="Tambade", Email="rTambade@gmail.com", ContactNumber="35434", Password="ravi@123"});
        // emp.Add( new Employee(){ FirstName="Sachin", LastName="Nene", Email="", ContactNumber="sNene@gmail.com", Password="sachin@123"});
        // emp.Add( new Employee(){ FirstName="Shivani", LastName="Pande", Email="sPande@gmail.com", ContactNumber="56565464", Password="shivani@123"});
        // emp.Add( new Employee(){ FirstName="Madhu", LastName="Sharma", Email="mSharma@gmail.com", ContactNumber="342345", Password="madhu@123"});
        List<Employee> jsonEmployees = null;
        try{
            // // dynamic data type variable
            // var options=new JsonSerializerOptions {IncludeFields=true};
            // var produtsJson=JsonSerializer.Serialize<List<Employee>>(emp,options);
            // string fileName=@"D:\JAVA_SD\DotNet\dotnet\employee.json";
            // //Serialize all Flowers into json file

            // File.WriteAllText(fileName,produtsJson);
            //Deserialize from JSON file
            string fileName=@"D:\JAVA_SD\DotNet\dotnet\employee.json";
            string jsonString = File.ReadAllText(fileName);
            jsonEmployees = JsonSerializer.Deserialize<List<Employee>>(jsonString);
            Console.WriteLine("\n JSON :Deserializing data from json file\n \n");
              
    }
   catch(Exception exp){
    
    }
    finally{ }


        return jsonEmployees;
    }
}

firstmvc/passwordvalidation/Models/ErrorViewModel.cs
namespace passwordvalidation.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

firstmvc/passwordvalidation/Controllers/AuthController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using passwordvalidation.Models;
namespace passwordvalidation.Controllers;

public class AuthController : Controller
{
    private readonly ILogger<AuthController> _logger;

    public AuthController(ILogger<AuthController> logger)
    {
        _logger = logger;
    }
 
public IActionResult Login()
    {

        Console.WriteLine("in login method");
        return View();
    }
    public IActionResult Welcome()
    {

       // Console.WriteLine("in login method");
        return View();
    }

    public IActionResult Register()
    {
        Console.WriteLine("in register method");
        return View();
    }
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

firstmvc/passwordvalidation/Controllers/EmployeesController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using passwordvalidation.Models;
namespace passwordvalidation.Controllers;
using System.Collections.Generic;
using System.IO;
using System.Text.Json;
using System.Text.Json.Serialization;

public class EmployeesController : Controller
{
    private readonly ILogger<EmployeesController> _logger;

    public EmployeesController(ILogger<EmployeesController> logger)
    {
        _logger = logger;
    }

public IActionResult Postregister(string firstname,string lastname,string contact,string email,string pwd)
    {
        List<Employee> jsonEmployees=null;
         try{
            //Deserialize from JSON file
            string fileName=@"D:\JAVA_SD\DotNet\dotnet\employee.json";
            string jsonString = System.IO.File.ReadAllText(fileName);
            jsonEmployees = JsonSerializer.Deserialize<List<Employee>>(jsonString);
            Console.WriteLine("\n JSON :Deserializing data from json file\n \n");

            //adding new employee into list
            jsonEmployees.Add(new Employee() {FirstName=firstname, LastName=lastname, Email=email, ContactNumber=contact, Password=pwd});

             //Serialize all Flowers into json file
            var options=new JsonSerializerOptions {IncludeFields=true};
            var produtsJson=JsonSerializer.Serialize<List<Employee>>(jsonEmployees,options);
            System.IO.File.WriteAllText(fileName,produtsJson);
            Console.WriteLine("Employee registered successfully, check once");

            return Redirect("/employees/Index");
    }
   catch(Exception exp){
    
    }
    finally{ }


        return View();
    }

    
     public IActionResult Postlogin(string email,string password)

    {
        try{
            //Deserialize from JSON file
            string fileName=@"D:\JAVA_SD\DotNet\dotnet\employee.json";
            string jsonString = System.IO.File.ReadAllText(fileName);
            List<Employee> jsonEmployees = JsonSerializer.Deserialize<List<Employee>>(jsonString);
            Console.WriteLine("\n JSON :Deserializing data from json file\n \n");

        foreach( Employee employee in jsonEmployees){
            if(email == employee.Email && 
                                password==employee.Password){
             Console.WriteLine("successfull validation of employee..... ");
             Console.WriteLine("Redirecting to welcome..... ");   
            return Redirect("/Auth/Welcome");
           }
        }
    }
   catch(Exception exp){
    
    }
    finally{ }

        return View();
    }

    public IActionResult Index(){
        List<Employee>  allEmployees=EmployeeManager.GetAllEmployees();
        ViewData["catalog"]=allEmployees;
         return View();
    }

    
}

firstmvc/passwordvalidation/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using passwordvalidation.Models;
namespace passwordvalidation.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

firstmvc/passwordvalidation/Views/Employees/Index.cshtml
@{
    ViewData["Title"] = "Employee List";
}

<h1>Catalog</h1>
<hr/>
<div class="text-center">
    @{
        List<Employee> allEmployees=(List<Employee>)ViewData["catalog"]; 
        <ol>
            @foreach(Employee employee in allEmployees){
                <li>@employee.FirstName @employee.LastName</li>
            }
        </ol>
    } 
    <hr/>
</div>

firstmvc/passwordvalidation/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

<div class="text-center">
    <h1 class="display-4">Welcome...... You have successfully logged in....</h1> 
    <img src="/images/smile.jfif" width="100" height="100"/> 
</div>

firstmvc/passwordvalidation/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - passwordvalidation</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/passwordvalidation.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">passwordvalidation</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Login">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Register">Register</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employees" asp-action="Index">Employee List</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - passwordvalidation - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>